### PR TITLE
News article

### PR DESCRIPTION
**Pull request by Misori-simon**
## About the Project 

This project is about building a news article page about space Ripples Reveal Big Bang's Smoking Gun. Its a website clone from new york times magazine.

The features of this project are listed as below:
1. Website has a header:
    - With menu icon, NYT logo, and two buttons for subscribe and login. 
2. Have a news article in the main section. News story contains information like:
    - Publisher name
    - Published date.
    - Social icons to share the news.
    - Bookmark and comment  icons.
    - News story.
    - Button to view comments.
3. Editor's pick on right side to show specific news from the editor.
4. Grid section with more news.
5. Popular news on the right side.
6. Has a footer with 
   - Useful links like; News, Opinion, More, Arts, Living, and Subscribe.
   - Copy right information and other site-specific links.

### CODE REVIEW

**Comment by umairarshadbutt** [comment]
##
## Pull Request under review by Umair Arshad (TSE)

**Review by umairarshadbutt — CHANGES_REQUESTED** [review]
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @Misori-simon and @dipbazz
Such a remarkable project you made :+1: ! Awesome README :100: !
We, however, do have some few changes to carry out before we proceed (see review comment).

##

 For this project, we have to make sure nothing is messed up. Kindly work on the suggested changes 👇.

- [x] The NY Times logo is a link ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html)) ([screenshot](https://user-images.githubusercontent.com/29689273/94273983-8fa22b80-ff5e-11ea-9a83-89a598106bcd.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538403/))
Example:
``
- [x] **Editors’ Picks** aside should be aligned with respect to **Thanks for reading The Times.** ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html))
- [x] Footer should have a fixed position (it sticks to the bottom part of the screen [Example](https://user-images.githubusercontent.com/29689273/94274463-2cfd5f80-ff5f-11ea-88bf-7b043d865f93.png)) ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html)) ([screenshot](https://user-images.githubusercontent.com/29689273/94273983-8fa22b80-ff5e-11ea-9a83-89a598106bcd.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538403/))






##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you stick at any point or have any questions, let me know on slack at any time. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Review by javitocor — CHANGES_REQUESTED** [review]
#STATUS CHANGES REQUIRED ♻️ 

Good job with the changes, team! 👍 
But still, one more thing to fix.
Check my comments below 👇 , apply the changes required and resubmit for a new code review ⏩

Good luck 😃  

- Kindly, fix the editor's picks, now it is overlapping the text, position it a bit more to the right
Capture

**Comment by umairarshadbutt** [comment]
##
## Pull Request under review by Umair Arshad (TSE)

**Review by umairarshadbutt — APPROVED** [review]
# **Status: PROJECT APPROVED** :champagne:
Excellent job on this project guys. :fireworks: Keep it up.
##
### The [clone](https://misori-simon.github.io/Positioning-and-Floating-Elements/) shows a good understanding of Positioning and Floating Elements. :100:
##
- The cloned page is rendering as it should and meets all the project specifications.
- The project has a descriptive README.md and is professionally done. Good job with that.
- The repo has followed all the guidelines there are to follow (GitHub flow etc.)
**All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.**
- Congratulations on the splendid job @Misori-simon and @dipbazz ! :+1: 
- You can now merge to master and submit the project completion form :rocket: . I wish you all the very best in your next tasks :1st_place_medal:
##
**If you have any questions, let me know on slack at any time. I will be happy to help.**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Pull request merged**
